export const CONVERT_STARTED = 'CONVERT_STARTED';
export const CONVERT_FINISHED = 'CONVERT_FINISHED';
export const CONVERT_FAILED = 'CONVERT_FAILED';

export const MESSAGE_STARTED = 'MESSAGE_STARTED';
export const MESSAGE_FINISHED = 'MESSAGE_FINISHED';
export const MESSAGE_FAILED = 'MESSAGE_FAILED';
